spring:
  application:
    name: user-service

  profiles:
    active: local

---
# local 프로파일
spring:
  profiles: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XEPDB1
    username: ORDER_SERVICE
    password: order123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true


services:
  user-service:
    url: http://localhost:8081
  product-service:
    url: http://localhost:8082

server:
  port: 8083

---
# Docker Profile
spring:
  profiles: docker
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:oracle-db}:${DB_PORT:1521}:${DB_SID:XEPDB1}
    username: ${DB_USERNAME:ORDER_SERVICE}
    password: ${DB_PASSWORD:order123}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:8080}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://product-service:8080}


server:
  port: 8080