spring:
  application:
    name: user-service

  profiles:
    active: local

---
# local 프로파일
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:oracle-db}:${DB_PORT:1521}/XEPDB1
    username: PRODUCT_SERVICE
    password: product123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8082

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:oracle-db}:${DB_PORT:1521}/XEPDB1
    username: PRODUCT_SERVICE
    password: product123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8080