-- ===================================
-- PDB 환경에서 마이크로서비스별 사용자 생성
-- ===================================

-- CDB$ROOT에서 XEPDB1으로 이동
ALTER SESSION SET CONTAINER = XEPDB1;

-- User Service 사용자 생성 (PDB 환경에서는 C## 접두사 불필요)
CREATE USER USER_SERVICE IDENTIFIED BY user123;

-- Product Service 사용자 생성
CREATE USER PRODUCT_SERVICE IDENTIFIED BY product123;

-- Order Service 사용자 생성
CREATE USER ORDER_SERVICE IDENTIFIED BY order123;

-- ===================================
-- 권한 부여
-- ===================================

-- User Service 권한
GRANT CONNECT, RESOURCE TO USER_SERVICE;
GRANT CREATE SESSION TO USER_SERVICE;
GRANT CREATE TABLE TO USER_SERVICE;
GRANT CREATE SEQUENCE TO USER_SERVICE;
GRANT CREATE TRIGGER TO USER_SERVICE;
GRANT CREATE VIEW TO USER_SERVICE;

-- Product Service 권한
GRANT CONNECT, RESOURCE TO PRODUCT_SERVICE;
GRANT CREATE SESSION TO PRODUCT_SERVICE;
GRANT CREATE TABLE TO PRODUCT_SERVICE;
GRANT CREATE SEQUENCE TO PRODUCT_SERVICE;
GRANT CREATE TRIGGER TO PRODUCT_SERVICE;
GRANT CREATE VIEW TO PRODUCT_SERVICE;

-- Order Service 권한
GRANT CONNECT, RESOURCE TO ORDER_SERVICE;
GRANT CREATE SESSION TO ORDER_SERVICE;
GRANT CREATE TABLE TO ORDER_SERVICE;
GRANT CREATE SEQUENCE TO ORDER_SERVICE;
GRANT CREATE TRIGGER TO ORDER_SERVICE;
GRANT CREATE VIEW TO ORDER_SERVICE;

-- ===================================
-- 테이블스페이스 할당
-- ===================================

-- 무제한 테이블스페이스 할당
ALTER USER USER_SERVICE QUOTA UNLIMITED ON USERS;
ALTER USER PRODUCT_SERVICE QUOTA UNLIMITED ON USERS;
ALTER USER ORDER_SERVICE QUOTA UNLIMITED ON USERS;

-- 로그 출력
PROMPT 'Microservice users created successfully in XEPDB1!';